version: '3'

services:
    core:
        container_name: "roscore"
        build:
            context: ./
            dockerfile: ./docker/ros/Dockerfile
        volumes:
            - ./src:/home/catkin_ws/src
        command:
            - roscore
